export const initialState = {
  name: "",
  birthday: "",
  contract: "",
  jmbg: "",
  bankAccountOne: "",
  bankAccountTwo: "",
  eyes: "",
  safety: "",
  fire: "",
  firstAid: "",
  jobRole: "",
  skills: [""],
  paycheck: "",
  bonus: "",
  benefitUser: "",
  healthDate: "",
  fitpassDate: "",
  comment: "",
};
